#!/usr/bin/env python3
"""Generate the launcher icon and the 512² Play listing asset from `rabbit.py`.

Writes, all of them derived and none of them hand-editable:

    app/src/main/res/drawable/ic_launcher_foreground.xml
    app/src/main/res/drawable/ic_launcher_monochrome.xml
    app/src/main/res/mipmap-{m,h,xh,xxh,xxx}dpi/ic_launcher{,_round}.webp
    art/play-icon-512.png

`ic_launcher_background.xml` is left alone — it is a flat GREEN rectangle with no art in it.

    python3 art/make-launcher-icon.py
"""

from pathlib import Path

from PIL import Image, ImageDraw

import rabbit

ART = Path(__file__).parent
RES = ART.parent / "app/src/main/res"

CANVAS = 108  # adaptive-icon canvas, in dp
VISIBLE = 72  # the most any launcher shows of it — what the flat assets are cropped to
ART_SIZE = 60  # longest side of the mark

# A launcher may mask the icon down to a 66dp circle, so anything outside that is at risk.
# The mark is tall and narrow, which means its bounding-box corners fall outside the circle
# while the art in them does not: the top of the box holds two narrow ears near the centre
# line and the bottom holds a rounded body. Fitting the *box* inside the circle instead would
# shrink the rabbit to about 45dp for no gain.
SAFE_DIAMETER = 66

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SS = 20  # supersample factor for the raster assets

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  The Binky rabbit. Original art, built from ellipses declared in art/rabbit.py and
  generated by art/make-launcher-icon.py — regenerate rather than editing the path data
  here. The eye is a hole in the path, not a painted shape, so it survives the monochrome
  layer's flat tint.
-->
"""

VECTOR = """{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path
      android:fillColor="{colour}"
      android:pathData="{data}" />
</vector>
"""


def hex_of(rgb):
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def vector_path_data():
    tf = rabbit.fit(CANVAS, ART_SIZE)
    return "".join(rabbit.path_data(e, tf) for e in rabbit.PARTS)


def render(size, mask_circle=False):
    """The composed icon — green ground, cream rabbit — cropped to the visible 72dp."""
    big = CANVAS * SS
    img = Image.new("RGBA", (big, big), rabbit.GREEN + (255,))
    d = ImageDraw.Draw(img)
    tf = rabbit.fit(CANVAS * SS, ART_SIZE * SS)
    for e in rabbit.PARTS:
        # On the flat assets the hole is simply painted back to the ground colour; the
        # winding trick only matters where something else shows through.
        colour = (rabbit.GREEN if e.hole else rabbit.CREAM) + (255,)
        d.polygon(rabbit.outline(e, tf), fill=colour)

    inset = (CANVAS - VISIBLE) // 2 * SS
    img = img.crop((inset, inset, big - inset, big - inset)).resize((size, size), Image.LANCZOS)

    if mask_circle:
        mask = Image.new("L", (size * 4, size * 4), 0)
        ImageDraw.Draw(mask).ellipse((0, 0, size * 4 - 1, size * 4 - 1), fill=255)
        img.putalpha(mask.resize((size, size), Image.LANCZOS))
    return img


def main():
    data = vector_path_data()
    written = []

    for name, colour in (
        ("ic_launcher_foreground", hex_of(rabbit.CREAM)),
        ("ic_launcher_monochrome", "#FFFFFF"),
    ):
        path = RES / "drawable" / f"{name}.xml"
        path.write_text(VECTOR.format(header=HEADER, colour=colour, data=data))
        written.append(path)

    for density, size in DENSITIES.items():
        for name, circle in (("ic_launcher", False), ("ic_launcher_round", True)):
            path = RES / f"mipmap-{density}" / f"{name}.webp"
            render(size, mask_circle=circle).save(path, "WEBP", lossless=True, quality=100)
            written.append(path)

    play = ART / "play-icon-512.png"
    render(512).convert("RGB").save(play, "PNG", optimize=True)  # Play rejects alpha
    written.append(play)

    x0, y0, x1, y1 = rabbit.bounds()
    w, h = x1 - x0, y1 - y0
    scale = ART_SIZE / max(w, h)
    half_diag = ((w * scale) ** 2 + (h * scale) ** 2) ** 0.5 / 2
    print(f"mark {w:.0f}x{h:.0f} -> {w * scale:.1f}x{h * scale:.1f}dp on a {CANVAS}dp canvas")
    print(f"bounding-box half-diagonal {half_diag:.1f}dp vs {SAFE_DIAMETER / 2:.0f}dp safe radius")
    print(f"path data {len(data)} chars")
    for p in written:
        print(f"  {p.relative_to(ART.parent)}")


if __name__ == "__main__":
    main()
