"""The Binky rabbit: the single definition of the mark.

Both generators import this — the launcher icon emits it as `VectorDrawable` path data, the
feature graphic rasterises it with PIL — so the two cannot drift into being different rabbits.

Provenance: the mark was generated by an image model from the brief in `art/logo-brief.md` —
our own prompt, not a stock icon, an emoji font, or anyone else's mark — and converted to the
curves below by `art/trace-mark.py`. No third-party art is involved. That is the property the
old Noto-traced icon lacked, and lacking it is what blocked the first Play upload.

The geometry is two subpaths: the rabbit, and the eye punched out of it. Coordinates are in
arbitrary units around an origin at the mark's centre; callers fit them to their own canvas
with `fit()`. y grows downward, as it does in both SVG and PIL.
"""

import re
from dataclasses import dataclass

# The identity's colours, from the Phase 7 light scheme so the icon and the app agree. The
# rabbit is near-white, so the ground carries all the colour: recolouring the mark means ROSE
# here and the matching fillColor in res/drawable/ic_launcher_background.xml, which this
# generator deliberately does not write.
CREAM = (0xFF, 0xF8, 0xEF)  # `surface`
ROSE = (0x69, 0x32, 0x38)  # `primary`, darkened for contrast against CREAM at icon sizes
ROSE_DARK = (0x34, 0x19, 0x1C)  # second stop of the feature graphic's gradient


@dataclass(frozen=True)
class Subpath:
    """One closed contour, as cubic path data.

    `d` is always wound CLOCKWISE on screen (positive shoelace area with y downward). A hole
    is stored the same way and reversed at read time by `nodes()`, so it is subtracted by the
    non-zero fill rule that both SVG and VectorDrawable use by default. That is what makes the
    eye a real hole rather than a shape painted in the background colour — and it is why the
    eye survives the monochrome layer, where Android tints everything one flat colour and a
    painted eye would simply vanish.
    """

    d: str
    hole: bool = False


# A sitting rabbit facing right, traced from the concept art. One outer contour and the eye.
MARK = (
    "M42.88,-61.69C38.21,-74.78 37.87,-77.87 30.22,-90.09"
    "C27.33,-94.7 24.07,-99.08 20.6,-103.26C17.83,-106.58 13.7,-108.8 11.54,-112.55"
    "C9.74,-115.67 9.84,-119.56 9.18,-123.11C8.94,-124.42 8.75,-125.75 8.84,-127.08"
    "C9.03,-129.96 9.37,-132.85 10.01,-135.66C11,-140 15.98,-138.68 18.62,-137.16"
    "C26.81,-132.45 30.75,-129.74 37.27,-122.45C48.27,-110.17 55.22,-94.12 58.93,-78.2"
    "C60.16,-72.96 60.47,-67.5 62.04,-62.35C62.29,-61.53 63.36,-61.16 64.19,-60.93"
    "C66.77,-60.19 69.51,-60.15 72.11,-59.49C79.11,-57.72 84.38,-55.7 90.61,-51.94"
    "C103.48,-44.17 113.29,-30.88 116.42,-16.12C118.95,-4.17 114.39,8.31 104.45,15.58"
    "C89.87,26.26 104.97,14.52 92.59,21.92C92.03,22.26 91.42,22.86 91.45,23.51"
    "C91.73,29.27 93.4,34.92 93.49,40.68C93.65,51.21 91.15,62.6 87.45,72.38"
    "C84.3,80.7 79.8,88.48 76.72,96.82C75.07,101.29 74.13,106 73.3,110.69"
    "C73,112.42 72.5,114.42 73.34,115.97C74.69,118.46 77.64,119.7 79.38,121.92"
    "C81.27,124.34 85.9,133.77 81.36,136.34C76.09,139.31 69.18,136.54 63.53,136.36"
    "C56.89,136.14 48.4,140 42.39,136.42C39.34,134.61 41.29,129.4 40.84,125.88"
    "C39.54,115.83 36.96,105.65 30.6,97.48C25.06,90.36 17.57,84.37 8.71,81.97"
    "C5.5,81.1 0.58,78.86 -1.27,81.63C5.65,85.57 7.95,86.14 13.33,92.08"
    "C20.9,100.43 24.59,112.11 24.56,123.24C24.55,126.56 23.9,129.85 23.43,133.15"
    "C23.35,133.72 22.88,135.93 21.92,136.23C17.32,137.67 6.44,136.4 4.09,136.41"
    "C-1.37,136.43 -6.31,136.25 -11.77,136.32C-15.08,136.36 -18.36,137.07 -21.67,137.07"
    "C-38.65,137.11 -54.66,136.17 -71.87,136.38C-76.47,136.44 -81.73,137.55 -86.4,136.72"
    "C-102.38,133.89 -118.95,118.02 -111.03,100.78C-110.2,98.98 -108.86,97.44 -107.53,95.97"
    "C-105.29,93.47 -101.63,91.61 -98.29,91.28C-93.56,90.81 -96.28,92.2 -94.06,90.88"
    "C-93.9,79.19 -93.2,68.5 -89.95,57.19C-81.58,28.07 -60.97,4.9 -32.9,-6.37"
    "C-26.28,-9.03 -17.16,-10.93 -10.44,-11.76C-5.63,-12.35 -0.72,-11.97 4.09,-12.63"
    "C10.96,-13.56 17.08,-18.29 19.61,-24.7C20.2,-26.19 20.73,-27.74 20.88,-29.33"
    "C21.21,-32.84 21.37,-36.39 21.04,-39.9C20.95,-40.89 20.49,-42 19.66,-42.54"
    "C13.84,-46.24 7.39,-48.88 1.44,-52.37C-15.3,-62.19 -30.55,-75.1 -40.38,-92.07"
    "C-44.13,-98.54 -48.21,-106.84 -48.96,-114.53C-49.16,-116.64 -49.3,-119.22 -48.03,-121.13"
    "C-46.91,-122.81 -43.85,-123.98 -42.15,-124.11C-30.63,-125.02 -21.9,-123.11 -11.1,-118.66"
    "C5.73,-111.72 19.38,-98.35 29.46,-83.49C34.56,-75.97 37.58,-68.53 42.39,-61.05"
    "C42.56,-61.26 42.72,-61.48 42.88,-61.69Z"
)

EYE = (
    "M77.33,-28.01C79.93,-28.37 80.23,-28.83 82.68,-27.48C87.87,-24.61 86.1,-16.56 80.7,-15.25"
    "C76.29,-14.18 72.34,-18.45 72.97,-22.72C73.4,-25.58 75.01,-26.79 77.33,-28.01Z"
)

PARTS = (
    Subpath(MARK),
    Subpath(EYE, hole=True),
)

_NUM = re.compile(r"-?\d*\.?\d+(?:e-?\d+)?")


def _points(d):
    """Path data -> the flat control-point list: 1 start point plus 3 per cubic segment."""
    pts = []
    for chunk in re.finditer(r"[MC]([^MCZz]*)", d):
        nums = [float(v) for v in _NUM.findall(chunk.group(1))]
        pts += list(zip(nums[0::2], nums[1::2]))
    return pts


def nodes(e, tf=lambda p: p):
    """Control points, caller-transformed, wound for fill or hole."""
    pts = _points(e.d)
    if e.hole:
        pts.reverse()
    return [tf(p) for p in pts]


def path_data(e, tf=lambda p: p, precision=2):
    """SVG/VectorDrawable path data for one subpath."""
    n = nodes(e, tf)

    def f(p):
        return f"{round(p[0], precision):g},{round(p[1], precision):g}"

    out = [f"M{f(n[0])}"]
    for i in range(1, len(n), 3):
        out.append("C" + " ".join(f(n[i + j]) for j in range(3)))
    return "".join(out) + "Z"


def outline(e, tf=lambda p: p, steps=32):
    """The same subpath flattened to a polygon, for renderers that can't draw curves."""
    n = nodes(e, tf)
    pts = []
    for i in range(1, len(n), 3):
        (x0, y0), (x1, y1), (x2, y2), (x3, y3) = n[i - 1], n[i], n[i + 1], n[i + 2]
        for s in range(steps):
            t = s / steps
            u = 1 - t
            pts.append((
                u * u * u * x0 + 3 * u * u * t * x1 + 3 * u * t * t * x2 + t * t * t * x3,
                u * u * u * y0 + 3 * u * u * t * y1 + 3 * u * t * t * y2 + t * t * t * y3,
            ))
    return pts


def bounds(parts=PARTS):
    """Bounding box of the silhouette. Holes are ignored — the eye cannot extend the mark."""
    xs, ys = [], []
    for e in parts:
        if e.hole:
            continue
        for x, y in outline(e):
            xs.append(x)
            ys.append(y)
    return min(xs), min(ys), max(xs), max(ys)


def fit(canvas, art_size, parts=PARTS):
    """A transform placing the mark centred on a square canvas at a given longest-side size.

    Returns a function mapping mark coordinates to canvas coordinates.
    """
    x0, y0, x1, y1 = bounds(parts)
    scale = art_size / max(x1 - x0, y1 - y0)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    return lambda p: (canvas / 2 + (p[0] - cx) * scale, canvas / 2 + (p[1] - cy) * scale)
